os: linux
dist: xenial
language: node_js
os:
  - linux
node_js:
  - "10"
  - "12"
addons:
  apt:
    sources:
      - llvm-toolchain-r-test
    packages:
      - clang-5.0
env:
  global:
    - CXX=clang++-5.0
    - CC=clang-5.0
    - _FORCE_LOGS=1
install:
  # on node 12 opencv4nodejs and mjpeg-consumer cannot be installed
  - if [[ `node --version` != v12* ]]; then
      printf "while [ true ]; do\nsleep 30\necho 'Building OpenCV'\ndone" > ping.sh;
      bash ping.sh &
      echo $! > ping.pid;
      npm i opencv4nodejs > /dev/null 2>&1;
      kill `cat ping.pid`;

      npm install --no-save mjpeg-consumer;
    fi
  - npm install
script:
  - npm run test && npm run e2e-test
after_success:
  - npm run coverage
